
name: Push Run

on: 
  push

env:
  DOTS_DIR: dots

jobs:
  featurize_news:
    name: DT-OS_feat pipeline
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', 3.11]

    steps:

    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: Install test dependencies
      run: |
          python -m venv dots
          source dots/bin/activate
          python -m pip install --upgrade pip
          python -m spacy download en_core_web_sm
          python -m pip install -e .

    - name: gpy_feat tests
      run: |
          source dots/bin/activate
          python DOTS/test/test_dots_feat.py -n 100 -e 1 -d 0 -o dots_gpy_feats.csv
      env:
          OS_TOKEN: ${{ secrets.OS_TOKEN }}
    
    - name: distilroberta tests
      run: |
          source dots/bin/activate
          python -m spacy download en_core_web_sm
          python DOTS/test/test_dots_feat.py -n 100 -e 0 -d 0 -o dots_drba_feats.csv
      env:
          OS_TOKEN: ${{ secrets.OS_TOKEN }}

    - name: gliner tests
      run: |
          source dots/bin/activate
          python DOTS/test/test_dots_feat.py -n 100 -e 2 -d 0 -o dots_glnr_feats.csv
      env:
          OS_TOKEN: ${{ secrets.OS_TOKEN }}
        
    # - name: Minimal tests 2
    #   run: |
    #       source dots/bin/activate
    #       python -m spacy download en_core_web_sm
    #       python dots/dots_feat.py -n 5 -f 3 -s 1 -o dots_feats.csv
    #   env:
    #       OS_TOKEN: ${{ secrets.OS_TOKEN }}
    #       LOBSTR_KEY: ${{ secrets.LOBSTR_KEY }}
