
name: Push Run

on: 
  push

env:
  mlx_grph_DIR: mlx_grph

jobs:
  featurize_news:
    name: OS news featurize pipeline
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', 3.11]

    steps:

    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: Install test dependencies
      run: |
          python -m venv mlx_grph
          source mlx_grph/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -e .

    - name: Minimal tests
      run: |
          source mlx_grph/bin/activate
          python -m spacy download en_core_web_sm
          python mlx_grph/test_DT_feat.py
      env:
          OS_TOKEN: ${{ secrets.OS_TOKEN }}
        
    - name: Minimal tests 2
      run: |
          source mlx_grph/bin/activate
          python -m spacy download en_core_web_sm
          python mlx_grph/DT_feat.py -n 5 -f 3 -s 1 -o OS_feats.csv
      env:
          OS_TOKEN: ${{ secrets.OS_TOKEN }}
