
name: Push Run

on: 
  push

env:
  mlx_grph_DIR: mlx_grph

jobs:
  featurize_news:
    name: OpenSearch news, featurize, pipeline
    runs-on: ubuntu-latest

    steps:

    - name: Check-out mlx_grph repository
      uses: actions/checkout@v2
      with:
        repository: dcolinmorgan/mlx_grph
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.mlx_grph_DIR }}

    - name: Install test dependencies
      run: |
          python -m venv mlx_grph
          source mlx_grph/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -e .

      - name: Minimal tests
        run: |
            source mlx_grph/bin/activate
            python mlx_grph/test_DT_feat.py
